version: '3'

services:
  nginx_lb:
    container_name: load_balancer
    image: 'edbighead/nginx:medium'
    ports:
      - '8081:80'
  nginx_1:
    container_name: nginx_1
    image: 'nginx:1.17.6'
  nginx_2:
    container_name: nginx_2
    image: 'nginx:1.17.6'
  nginx_3:
    container_name: nginx_3
    image: 'nginx:1.17.6'
